### PR TITLE
feat(config): set defaults with env vars

### PR DESCRIPTION
**Pull request by JosephKav**
Allows you to set hard defaults via env vars. These are last in priority after defaults specified in the config YAML. Formatting for these vars is `ARGUS_` followed by the YAML tag format in uppercase with `_` delimeters. e.g.
`ARGUS_SERVICE_LATEST_VERSION_ACCESS_TOKEN` for a default on `defaults.service.latest_version.access_token` in the YAML

### CODE REVIEW

**Comment by initharrington** [comment]
Hi @JosephKav,

I am unable to get this to work.  Can you explain how I should set the `env` variable in the config? (docker build from master)

I know it doesn't work this way but this how I was thinking about it.  You should be able to set **any** env variable name in the container, set the config file to use the **same** env variable, and argus would on load, do a find/replace in the config.  This is how other services I use work.

Example:

```
  extraSecretEnvironmentVars:
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: argus-secrets
          key: GITHUB_ACCESS_TOKEN
```
```
    service:
      argus:
        latest_version:
          type: github
          access_token: $GITHUB_ACCESS_TOKEN
          url: release-argus/argus
```

The error from the pod logs:

```
ERROR: argus, github access token is invalid
```

When I do:

```
  extraSecretEnvironmentVars:
    - name: ARGUS_SERVICE_LATEST_VERSION_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: argus-secrets
          key: GITHUB_ACCESS_TOKEN
```
```
    service:
      argus:
        latest_version:
          type: github
          url: release-argus/argus
```

Error, its not passing the auth information in the header:
```
ERROR: argus, Get "https://api.github.com/repos/release-argus/argus/releases": net/http: invalid header field value for "Authorization"
```

Doing this in the config doesn't work either:

```
    service:
      argus:
        latest_version:
          type: github
          access_token: $ARGUS_SERVICE_LATEST_VERSION_ACCESS_TOKEN
          url: release-argus/argus
```

It isn't clear what I should put in the config.

Thanks

**Comment by initharrington** [comment]
That is what I thought I was doing:

From http://localhost:8000/api/v1/version

```
{"version":"development","buildDate":"2023-05-23T18:33:27Z","goVersion":"go1.20.4"}
```

My config:

```
  config: |
    settings:
      log:
        level: DEBUG
    service:
      argus:
        latest_version:
          type: github
          url: release-argus/argus
        deployed_version:
          url: http://localhost:8080/api/v1/version
          json: version
        dashboard:
          icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
          web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
```

Logs:

```
Switching user UID:GID to 911:911
Applying perms to config.yml and argus.db
Starting...
DEBUG: 1/1 argus Init
INFO: Found 1 services to monitor:
  - argus
VERBOSE: argus, Tracking argus at https://github.com/release-argus/argus every 10m
ERROR: argus, Get "https://api.github.com/repos/release-argus/argus/releases": net/http: invalid header field value for "Authorization"
INFO: Listening on 0.0.0.0:8080/
VERBOSE: httpVersion (127.0.0.1), -
ERROR: argus, failed converting "development" to a semantic version. If all versions are in this style, consider adding json/regex to get the version into the style of 'MAJOR.MINOR.PATCH' (https://semver.org/), or disabling semantic versioning (globally with defaults.service.semantic_versioning or just for this service with the semantic_versioning var)
VERBOSE: httpVersion (127.0.0.1), -
VERBOSE: httpVersion (127.0.0.1), -
```
My environment variables:

```
# env | grep ARGUS
ARGUS_SERVICE_HOST=<REDACTED>
ARGUS_SERVICE_LATEST_VERSION_ACCESS_TOKEN=ghp_<REDACTED>
ARGUS_SERVICE_PORT=80
ARGUS_PORT=tcp://<REDACTED>:80
ARGUS_PORT_80_TCP_ADDR=1<REDACTED>
ARGUS_PORT_80_TCP_PORT=80
ARGUS_PORT_80_TCP_PROTO=tcp
ARGUS_PORT_80_TCP=tcp://<REDACTED>:80
ARGUS_SERVICE_PORT_HTTP=80
```

I can try outside of k8s tomorrow.

**Comment by w00dst0ck** [comment]
@JosephKav 

Unfortunately, this approach seems not helpful for all cases.

In my current case a header with the following name is needed. 
HTTP Header X-Rundeck-Auth-Token

However, the character "-" is not a valid character for a linux environment variable.

Am I missing something?
Is there a way to work with variables here?

```
deployed_version:
      url: https://rundeck.xxxxxx.xxx/api/14/system/info
      headers:
        - key: X-Rundeck-Auth-Token
          value: <access_token>
      regex: <build>(.*)<\/build>
```

**Comment by JosephKav** [comment]
@w00dst0ck, I haven't added support for lists, e.g. `deployed_version.headers` from env vars

**Pull request merged**
